title: Prueba github pages
description: Sitio de ejemplo
baseurl: ""
url: "https://marcramisg.github.io"
theme: jekyll-theme-minimal

plugins:                        
  - jekyll-feed
  - jekyll-seo-tag 

markdown: kramdown 
