title: Mi sitio con Jekyll
description: Este es un sitio de ejemplo
baseurl: ""
url: "https://marcramisg.github.io"
theme: jekyll-theme-minimal

plugins:                        
  - jekyll-feed
  - jekyll-seo-tag 

markdown: kramdown 
